// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using livestockProject.Models;

#nullable disable

namespace livestockProject.Migrations
{
    [DbContext(typeof(ModelContext))]
    partial class ModelContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("LIVESTOCK")
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("livestockProject.Models.Importedmeal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Count")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("COUNT");

                    b.Property<double>("Grossweight")
                        .HasColumnType("FLOAT")
                        .HasColumnName("GROSSWEIGHT");

                    b.Property<string>("Livestocktype")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("LIVESTOCKTYPE");

                    b.Property<string>("MealName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("MEAL_NAME");

                    b.Property<double>("Netweight")
                        .HasColumnType("FLOAT")
                        .HasColumnName("NETWEIGHT");

                    b.Property<string>("Origincountry")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ORIGINCOUNTRY");

                    b.Property<DateTime>("Shipmentarrivaldate")
                        .HasColumnType("DATE")
                        .HasColumnName("SHIPMENTARRIVALDATE");

                    b.Property<DateTime>("Shippingdate")
                        .HasColumnType("DATE")
                        .HasColumnName("SHIPPINGDATE");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("STATUS");

                    b.HasKey("Id");

                    b.ToTable("IMPORTEDMEAL", "LIVESTOCK");
                });

            modelBuilder.Entity("livestockProject.Models.SysModuel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("DescAr")
                        .IsRequired()
                        .HasMaxLength(120)
                        .IsUnicode(false)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("DESC_AR");

                    b.Property<string>("DescEn")
                        .IsRequired()
                        .HasMaxLength(120)
                        .IsUnicode(false)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("DESC_EN");

                    b.Property<int?>("IsActive")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("Moduleicon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("MODULEICON");

                    b.Property<string>("Moduleiconen")
                        .IsRequired()
                        .HasMaxLength(120)
                        .IsUnicode(false)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("MODULEICONEN");

                    b.HasKey("Id");

                    b.ToTable("SYS_MODUEL", "LIVESTOCK");
                });

            modelBuilder.Entity("livestockProject.Models.SystemCountry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("NameArabic")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("NAME_ARABIC");

                    b.HasKey("Id");

                    b.ToTable("SYSTEM_COUNTRY", "LIVESTOCK");
                });

            modelBuilder.Entity("livestockProject.Models.SystemLivestockType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("NameArabic")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("NAME_ARABIC");

                    b.HasKey("Id");

                    b.ToTable("SYSTEM_LIVESTOCK_TYPE", "LIVESTOCK");
                });

            modelBuilder.Entity("livestockProject.Models.SystemMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("DATE")
                        .HasColumnName("CREATED_DATE");

                    b.Property<string>("Createduser")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CREATEDUSER");

                    b.Property<DateTime?>("LastUpdateDate")
                        .HasColumnType("DATE")
                        .HasColumnName("LAST_UPDATE_DATE");

                    b.Property<string>("LastUpdatedUser")
                        .IsRequired()
                        .HasMaxLength(75)
                        .IsUnicode(false)
                        .HasColumnType("varchar(75)")
                        .HasColumnName("LAST_UPDATED_USER");

                    b.Property<string>("MenuController")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("MENU_CONTROLLER");

                    b.Property<bool?>("MenuFlag")
                        .HasPrecision(1)
                        .HasColumnType("bit")
                        .HasColumnName("MENU_FLAG");

                    b.Property<string>("MenuView")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("MENU_VIEW");

                    b.Property<string>("MenunameAr")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("MENUNAME_AR");

                    b.Property<string>("MenunameEn")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("MENUNAME_EN");

                    b.Property<string>("Menuorder")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("MENUORDER");

                    b.Property<int?>("ModuleId")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("MODULE_ID");

                    b.Property<int?>("PerantId")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("PERANT_ID");

                    b.Property<string>("SystemFunction")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("SYSTEM_FUNCTION");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.ToTable("SYSTEM_MENU", "LIVESTOCK");
                });

            modelBuilder.Entity("livestockProject.Models.SystemUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(1)
                        .HasColumnType("bit")
                        .HasColumnName("IS_ACTIVE")
                        .HasDefaultValueSql("1 \n");

                    b.Property<DateTime>("LastChangePassword")
                        .HasColumnType("DATE")
                        .HasColumnName("LAST_CHANGE_PASSWORD");

                    b.Property<DateTime>("LastLoginDate")
                        .HasColumnType("DATE")
                        .HasColumnName("LAST_LOGIN_DATE");

                    b.Property<string>("NameArabic")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("NAME_ARABIC");

                    b.Property<string>("NameEnglish")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("NAME_ENGLISH");

                    b.Property<string>("Upassword")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("UPASSWORD");

                    b.Property<int>("UserGroupId")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("USER_GROUP_ID");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("USERNAME");

                    b.HasKey("Id");

                    b.HasIndex("UserGroupId");

                    b.ToTable("SYSTEM_USERS", "LIVESTOCK");
                });

            modelBuilder.Entity("livestockProject.Models.SystemUserGroup", b =>
                {
                    b.Property<int>("UserGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("USER_GROUP_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserGroupId"), 1L, 1);

                    b.Property<int?>("MenuId")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("MENU_ID");

                    b.Property<string>("NameAr")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("NAME_AR");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("NAME_EN");

                    b.HasKey("UserGroupId")
                        .HasName("SYSTEM_USER_GROUP_PK");

                    b.ToTable("SYSTEM_USER_GROUP", "LIVESTOCK");
                });

            modelBuilder.Entity("livestockProject.Models.SystemMenu", b =>
                {
                    b.HasOne("livestockProject.Models.SysModuel", "Module")
                        .WithMany("SystemMenus")
                        .HasForeignKey("ModuleId")
                        .HasConstraintName("SYS_MENU_FK");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("livestockProject.Models.SystemUser", b =>
                {
                    b.HasOne("livestockProject.Models.SystemUserGroup", "UserGroup")
                        .WithMany("SystemUsers")
                        .HasForeignKey("UserGroupId")
                        .IsRequired()
                        .HasConstraintName("SYS_USER_FK");

                    b.Navigation("UserGroup");
                });

            modelBuilder.Entity("livestockProject.Models.SysModuel", b =>
                {
                    b.Navigation("SystemMenus");
                });

            modelBuilder.Entity("livestockProject.Models.SystemUserGroup", b =>
                {
                    b.Navigation("SystemUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
